"""add description to products

Revision ID: 18749e3cc8a6
Revises: 1d1c35b4994c
Create Date: 2018-07-12 11:22:28.624958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18749e3cc8a6'
down_revision = '1d1c35b4994c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
